language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: PJrnJHhOhk5mnbUnLZZ2QMz+Ri/o5lW+K/eXnN5DzG5HVazkYYRgtLrgjXVnSsN3LS8giFp6p+3Yjy9dRTRNP5/0pOH2d73CN5Nscn70vgxsBs9v4kG2wrIPEpfm7dVrFCw0+Irr9Lau0XaU0kxJMOsJW1BFqdYT47n0AIOHg6eN/KiFfnvUNhgpXPW9Wk8EbNwdvxCDKoPOKhwHL9rBgvtSMv/75PIiL1r8pmY952broOiXrXOGZbE1ZnpR+Rv28HNIb5GN66g/RSws9JGhC49Re9SbOSR65SxyXk8tBTE3Y6vn8dM52V2nJCmT33nMkDvtrW79minS3Xw3XexXDcdYkf44zXImJSnmzpmWJXXL78sHcW3E+kINsMFwc7TM1vwdSPOVlzBC2tSHFYiw8Yu3xgBlGJqEuztPjQZkzpf/yfZvBBtGHhlVyjEIycR1zekChVg/BsOKf0Dk+V+aHUh7qQbQ/1XhwZZoL4uaF/cUJ4C+SzLP/xFyCV1xmHnIcCFtUZaCtPvmRFXnCkvL42wFOCLgUg4H4v49Z5vqvbc5QJpHYMjDQgT/6it0hEaG1wcsua44av3i6b0d7OG/uzGZh13E3PmU43w9Uvtk6GUGb51ZwI9Rx4OYobCHjogsrVFtsitpIXdb6r9bd/He6T2Z5b1tTvtnTGJruD+aRBg=
  app: sample-kirrok
